
[package]
name = "nadi_futures"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

# make sure you use the same version of nadi_core, your nadi-system is in
[dependencies]
abi_stable = "0.11.3"
nadi_core = "0.7.0"
